CREATE SCHEMA `db_todo` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
CREATE TABLE `db_todo`.`todos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `task` VARCHAR(300) NOT NULL,
  `done` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;
